<Project>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

		<!-- Engine Information -->
		<EngineName>Principle Engine</EngineName>
        <EngineVersion>0.1.0</EngineVersion>
		
		<!-- Editor Information -->
		<EditorName>Principle Editor</EditorName>
        <EditorVersion>0.1.0-alpha</EditorVersion>
    </PropertyGroup>
</Project>
