<Project>
  
  <PropertyGroup>
    
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<!-- Engine Information -->
		<EngineName>Principle Engine</EngineName>
    <EngineVersion>0.1.0</EngineVersion>
		
		<!-- Editor Information -->
		<EditorName>Principle Editor</EditorName>
    <EditorVersion>0.1.0-alpha</EditorVersion>
    
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Meziantou.Analyzer"
                      Version="3.0.140"
                      PrivateAssets="all" />
    <PackageReference Include="SonarAnalyzer.CSharp"
                          Version="10.31.0.145097"
                          PrivateAssets="all" />
    
    
  </ItemGroup>
  
</Project>
