<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Principle.API.csproj" />
    <ProjectReference Include="..\Principle.Renderer\Principle.Renderer.csproj" />
  </ItemGroup>

</Project>
