<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Principle.Platform/Principle.Platform.csproj" />
    <ProjectReference Include="../Principle.Rendering.Abstractions/Principle.Rendering.Abstractions.csproj" />
    <ProjectReference Include="../Principle.Rendering/Principle.Rendering.csproj" />
  </ItemGroup>
</Project>
