<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET" Version="2.23.0" />
        <PackageReference Include="Veldrid" Version="4.8.0" />
        <PackageReference Include="Veldrid.StartupUtilities" Version="4.8.0" />
        <PackageReference Include="Veldrid.SPIRV" Version="1.0.13" />
    </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Shaders\**\*.glsl" />
	</ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine\Principle.API.csproj" />
    </ItemGroup>

</Project>
